name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: prerequisites
      run: sudo apt-get update && sudo apt-get install xorg libxext-dev zlib1g-dev libbsd-dev
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.CHIMPANSKY_LIBFT_PAT }}
    - name: make
      run: make
